- name: "create docker service with {% if intermediate_configs is defined and intermediate_configs %}intermediate{% else %}final{% endif %} configs"
  docker_swarm_service:
    image: "{{ repository_deploy_image }}"
    name: "{{ inventory_hostname }}"
    hostname: "{{ inventory_hostname }}"
    limits:
      cpus: "{{ limit_cpu }}"
      memory: "{{ limit_memory }}"
    restart_config:
      condition: "{{ restart_policy }}"
    publish: "{{ publish | default(omit) }}"
    replicas: "{{ replicas | default(omit) }}"
    # XXX - stupid naming
    mounts: "{{ docker_service_templated_config.volumes }}"
    configs: "{% if intermediate_configs is defined and intermediate_configs %}{{ docker_service_templated_config.intermediate_configs }}{% else %}{{ docker_service_templated_config.configs }}{% endif %}"
    state: "{{ state|default(omit) }}"
    # require user to be specified, because defaults to root pre-2.8, overriding the image configuration
    user: "{{ user }}"
    logging:
      driver: "{{ log_driver | default(omit) }}"
      options: "{{ log_driver_options | default(omit) }}"
    env: "{{ env | default(omit) }}"
  become: "{{ docker_become_user is defined }}"
  become_user: "{{ docker_become_user|default(omit) }}"
  # tagged to allow skipping to allow only management of volumes
  tags:
    - service
